spring.application.name=notificaciones-service
server.port=8084

# Este servicio NO persiste nada: sin datasource ni JPA.

spring.kafka.bootstrap-servers=localhost:29092

spring.kafka.consumer.group-id=notificaciones-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.zv.*
spring.kafka.consumer.properties.spring.json.use.type.headers=false

app.kafka.topics.pago-aprobado=pagos.aprobado
app.kafka.topics.pedido-cancelado=pedidos.cancelado

logging.level.com.zv=DEBUG
logging.level.org.apache.kafka=WARN